global.constants = {
    platform:"/platform",
    crm:"/crm",
    sinoboom:"/sinoboom",
    tbase:"/tbase",
    menus:[
        {
            id:"SYSTEM_HOME",
            name:'我的工作台',
            className:'top-menus-button-img-portal',
            url:'/frame/home',
            childs:[],
            public:true,
        },
        {
            id:"SYSTEM_MANAGE",
            name:'系统设定',
            className:'top-menus-button-img-system',
            url:'',
            public:false,
            childs:[
                {
                    id:"RESOURCE_LIST",
                    name:"系统资源",
                    className:"ui-profile-navLeft-item-io",
                    url:"/frame/resource",
                    authority:"RESOURCE_LIST"
                },
                {
                    id:"AUTHORITY_GROUP_LIST",
                    name:"权限组",
                    className:"ui-profile-navLeft-item-authorize",
                    url:"/frame/authgrp",
                    authority:"AUTHORITY_GROUP_LIST"
                },
                {
                    id:"AUTHORITY_LIST",
                    name:"权限定义",
                    className:"ui-profile-navLeft-item-authority",
                    url:"/frame/authority",
                    authority:"AUTHORITY_LIST"
                },
                {
                    id:"ROLE_LIST",
                    name:"角色定义",
                    className:"ui-profile-navLeft-item-cogroup",
                    url:"/frame/role",
                    authority:"ROLE_LIST"
                },
                {
                    id:"ACCESS_LOG_LIST",
                    name:"访问日志",
                    className:"ui-profile-navLeft-item-user",
                    url:"/frame/accessLog",
                    authority:"ACCESS_LOG_LIST"
                }
            ] 
        },
        {
            id:"BASE_DATA",
            name:'基础数据',
            className:'top-menus-button-img-app',
            url:'',
            public:false,
            childs:[
                {
                    id:"POSITION_LIST",
                    name:"职务管理",
                    className:"ui-profile-navLeft-item-action",
                    url:"/base/position",
                    authority:"POSITION_LIST"
                },
                {
                    id:"ORG_LIST",
                    name:"组织架构",
                    className:"ui-profile-navLeft-item-organizationa",
                    url:"/base/org",
                    authority:"ORG_LIST"
                },
                {
                    id:"RULE_LIST",
                    name:"编码规则",
                    className:"ui-profile-navLeft-item-timing",
                    url:"/base/rule",
                    authority:"RULE_LIST"
                },
                {
                    id:"DICT_LIST",
                    name:"数据字典",
                    className:"ui-profile-navLeft-item-overview",
                    url:"/base/dict",
                    authority:"DICT_LIST"
                },
                {
                    id:"FILE_LIST",
                    name:"文件管理",
                    className:"ui-profile-navLeft-item-file",
                    url:"/base/file",
                    authority:"FILE_LIST"
                },
                {
                    id:"UNIT_LIST",
                    name:"计量单位",
                    className:"ui-profile-navLeft-item-mComponent",
                    url:"/base/unit",
                    authority:"UNIT_LIST"
                },
                {
                    id:"ATTRIBUTE_LIST",
                    name:"属性管理",
                    className:"ui-profile-navLeft-item-cogroup",
                    url:"/base/attribute",
                    authority:"ATTRIBUTE_LIST"
                },
                {
                    id:"CLASSIFICATION_LIST",
                    name:"分类管理",
                    className:"ui-profile-navLeft-item-timing",
                    url:"/base/classification",
                    authority:"CLASSIFICATION_LIST"
                },
                {
                    id:"STAFF_LIST",
                    name:"用户管理",
                    className:"ui-profile-navLeft-item-user",
                    url:"/base/staff",
                    authority:"STAFF_LIST"
                },
                {
                    id:"CODE_RANGE_LIST",
                    name:"号码段管理",
                    className:"ui-profile-navLeft-item-timing",
                    url:"/base/coderange",
                    authority:"CODE_RANGE_LIST"
                },
                {
                    id:"CODE_RANGE_DIS",
                    name:"号码段分配",
                    className:"ui-profile-navLeft-item-timing",
                    url:"/base/coderangedis",
                    authority:"CODE_RANGE_DIS"
                }
            ]
        },
        {
            id:"FINISHED_PRODUCT_MANAGE",
            name:'成品库存',
            className:'top-menus-button-img-modeling',
            url:'',
            public:false,
            childs:[
                {
                    id:"FINISHED_PRODUCT_LIST",
                    name:"成品库存",
                    className:"ui-profile-navLeft-item-io",
                    url:"/sinoboom/finished/product",
                    authority:"FINISHED_PRODUCT_LIST"
                }
            ] 
        },
        {
            id:"CUSTOMER_MANAGE",
            name:'客户管理',
            className:'top-menus-button-img-modeling',
            url:'',
            public:false,
            childs:[
                {
                    id:"CUSTOMER_LIST",
                    name:"客户信息",
                    className:"ui-profile-navLeft-item-io",
                    url:"/crm/customer/customer",
                    authority:"CUSTOMER_LIST"
                },
                {
                    id:"CONTOCTS_LIST",
                    name:"联系人",
                    className:"ui-profile-navLeft-item-authorize",
                    url:"/crm/customer/contocts",
                    authority:"CONTOCTS_LIST"
                },
                {
                    id:"COMPETITOR_LIST",
                    name:"竞争对手",
                    className:"ui-profile-navLeft-item-timing",
                    url:"/crm/customer/competitor",
                    authority:"COMPETITOR_LIST"
                },
                {
                    id:"PRODUCT_CATEGORY_LIST",
                    name:"产品类别",
                    className:"ui-profile-navLeft-item-mComponent",
                    url:"/crm/product/category",
                    authority:"PRODUCT_CATEGORY_LIST"
                },
                {
                    id:"PRODUCT_LIST",
                    name:"产品数据",
                    className:"ui-profile-navLeft-item-overview",
                    url:"/crm/product/product",
                    authority:"PRODUCT_LIST"
                }
            ] 
        },
        {
            id:"BUSINESS_MANAGE",
            name:'业务管理',
            className:'top-menus-button-img-notify',
            url:'',
            public:false,
            childs:[
                {
                    id:"LEADS_LIST",
                    name:"线索管理",
                    className:"ui-profile-navLeft-item-io",
                    url:"/crm/business/leads",
                    authority:"LEADS_LIST"
                },
                {
                    id:"BUSINESS_LIST",
                    name:"商机管理",
                    className:"ui-profile-navLeft-item-authorize",
                    url:"/crm/business/business",
                    authority:"BUSINESS_LIST",
                    childs:[
                        {
                            id:"BUSINESS_RISE",
                            name:"商机跟进",
                            url:"/crm/business/rise",
                            authority:"BUSINESS_RISE",
                        }
                    ]
                },
                {
                    id:"BUSINESS_TYPE_LIST",
                    name:"商机阶段",
                    className:"ui-profile-navLeft-item-overview",
                    url:"/crm/business/type",
                    authority:"BUSINESS_TYPE_LIST"
                },
                {
                    id:"CARES_LIST",
                    name:"客户关怀",
                    className:"ui-profile-navLeft-item-timing",
                    url:"/crm/customer/cares",
                    authority:"CARES_LIST"
                },
                {
                    id:"CONTOCTS_RECORD_LIST",
                    name:"联系记录",
                    className:"ui-profile-navLeft-item-mComponent",
                    url:"/crm/customer/record",
                    authority:"CONTOCTS_RECORD_LIST"
                }
            ] 
        }
    ]
}